-- Faturas detalhadas e emissão manual
-- Execute depois de 202608040001_modelos_faturamento.sql.

alter table public.configuracoes
  add column if not exists escola_nome text,
  add column if not exists escola_documento text,
  add column if not exists escola_email text,
  add column if not exists escola_telefone text,
  add column if not exists escola_cep text,
  add column if not exists escola_endereco text,
  add column if not exists escola_numero text,
  add column if not exists escola_complemento text,
  add column if not exists escola_bairro text,
  add column if not exists escola_cidade text,
  add column if not exists escola_estado text;

update public.configuracoes
set escola_nome = coalesce(nullif(trim(escola_nome), ''), 'Lotus Music')
where id = 1;

alter table public.faturas
  add column if not exists numero bigint generated by default as identity,
  add column if not exists tipo_emissao text not null default 'AUTOMATICA',
  add column if not exists periodo_inicio date,
  add column if not exists periodo_fim date,
  add column if not exists observacoes text,
  add column if not exists aluno_nome text,
  add column if not exists aluno_documento text,
  add column if not exists aluno_email text,
  add column if not exists aluno_telefone text,
  add column if not exists aluno_endereco text,
  add column if not exists emitente_nome text,
  add column if not exists emitente_documento text,
  add column if not exists emitente_email text,
  add column if not exists emitente_telefone text,
  add column if not exists emitente_endereco text;

alter table public.faturas
  drop constraint if exists faturas_tipo_emissao_check,
  add constraint faturas_tipo_emissao_check
    check (tipo_emissao in ('AUTOMATICA', 'MANUAL')),
  drop constraint if exists faturas_aluno_competencia_modelo_uidx;

create unique index if not exists faturas_numero_uidx
  on public.faturas(numero);

create unique index if not exists faturas_fechamento_mensal_uidx
  on public.faturas(aluno_id, competencia, modelo_faturamento)
  where tipo_emissao = 'AUTOMATICA'
    and modelo_faturamento = 'MENSAL_FECHADO';

alter table public.historico_aulas
  add column if not exists professor_id uuid references public.profiles(id) on delete set null,
  add column if not exists modalidade text,
  add column if not exists fatura_id uuid references public.faturas(id) on delete set null,
  add column if not exists faturado_em timestamptz;

create index if not exists historico_aulas_pendentes_faturamento_idx
  on public.historico_aulas(aluno_id, data_aula)
  where fatura_id is null;

create table if not exists public.fatura_itens (
  id uuid primary key default gen_random_uuid(),
  fatura_id uuid not null references public.faturas(id) on delete cascade,
  historico_aula_id text,
  data_aula date not null,
  horario_inicio time,
  horario_fim time,
  modalidade text not null,
  professor_id uuid references public.profiles(id) on delete set null,
  professor_nome text not null,
  descricao text,
  quantidade numeric(10, 2) not null default 1,
  valor_unitario numeric(12, 2) not null default 0,
  valor_total numeric(12, 2) not null default 0,
  criado_em timestamptz not null default now(),
  constraint fatura_itens_quantidade_check check (quantidade > 0),
  constraint fatura_itens_valores_check check (valor_unitario >= 0 and valor_total >= 0)
);

create unique index if not exists fatura_itens_historico_uidx
  on public.fatura_itens(historico_aula_id)
  where historico_aula_id is not null;

create index if not exists fatura_itens_fatura_data_idx
  on public.fatura_itens(fatura_id, data_aula);

alter table public.fatura_itens enable row level security;

drop policy if exists "Itens de fatura visíveis para aluno e equipe" on public.fatura_itens;
create policy "Itens de fatura visíveis para aluno e equipe"
on public.fatura_itens for select
to authenticated
using (
  exists (
    select 1
    from public.faturas f
    where f.id = fatura_id
      and public.pode_acessar_dados_aluno(f.aluno_id)
  )
);

drop policy if exists "Equipe gerencia itens de fatura" on public.fatura_itens;
create policy "Equipe gerencia itens de fatura"
on public.fatura_itens for all
to authenticated
using (
  exists (
    select 1
    from public.faturas f
    where f.id = fatura_id
      and public.pode_acessar_dados_aluno(f.aluno_id)
      and auth.uid() <> f.aluno_id
  )
)
with check (
  exists (
    select 1
    from public.faturas f
    where f.id = fatura_id
      and public.pode_acessar_dados_aluno(f.aluno_id)
      and auth.uid() <> f.aluno_id
  )
);

grant select, insert, update, delete on public.fatura_itens to authenticated;
